host:
  public: 0.0.0.0
  private: 192.168.241.130
  local: 127.0.0.1

spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://${host.private}:3306/order_sys_seller?zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: root
  jpa:
    databasePlatform: MYSQL
    hibernate:
      ddl-auto: none
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
      use-new-id-generator-mappings: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true

logging:
  path: F:/IDEA Project/seller
  file: ${logging.path}/seller
  config: classpath:logback-spring.xml
  level:
    com.glw.seller: info
